### ISSUE TITLE
Como adicionar blog?

### ISSUE THREAD

**Issue by pingfreud** [brbloggers/brbloggers-backend#1]
Olá, 

Tenho um blog sobre psiquiatria e neurociências clínicas. 

Uma sessão é dedicada a análise de dados e uso R:

https://d-van.org
https://d-van.org/analise/home

Feed:
https://medium.com/feed/d-van

É elegível para o r bloggers?

**Comment by dfalbel** [comment]
Claro! Vou adicionar!

**Comment by dfalbel** [comment]
Não consegui encontrar um feed específico p/ a sessão "analise" , tudo bem para você se eu pegar apenas os posts com a categoria: "análise-de-dados" ?
